# Generated by Django 4.2.3 on 2023-08-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0005_alter_perevaladded_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
