# Generated by Django 4.2.3 on 2023-08-26 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0006_alter_perevaladded_coord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='coord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perevals_added', to='pereval.coords'),
        ),
        migrations.AlterField(
            model_name='perevalimages',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pereval', to='pereval.images'),
        ),
        migrations.AlterField(
            model_name='perevalimages',
            name='pereval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval.perevaladded'),
        ),
    ]
