# Generated by Django 4.2.3 on 2023-08-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0010_alter_images_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
