# Generated by Django 4.2.3 on 2023-08-27 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0013_alter_image_pereval'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
    ]
